name: Generate WordCloud

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-wordcloud:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Profile WordCloud
        uses: Parply/profile-wordcloud@v0.0.1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          AUTHOR: minerva-jupiter
          CMAP: ocean
